### ISSUE TITLE
[remoteStorage+Sockethub] load existing invoice (if exists) on load

### ISSUE THREAD

**Issue by silverbucket** [noBackend/noBackend-app-invoice#5]
There was one more thing I wanted to add to the example. If there already are some invoices, it would be good to automatically load the last one rather than a new blank one.

How should I do that? render seems to load a new blank one, is there a way to indicate an object to use instead?

**Comment by gr2m** [comment]
I think it's actually a bug in app.js. I can't look into it at the moment, but I think it's adding a new blank invoice if you call `render()` and there is none yet. I've the same problem in the hoodie implementation

**Comment by gr2m** [comment]
that's fixed now, right?
