### ISSUE TITLE
Implement App with Dreamcode instead of Event Hooks

### ISSUE THREAD

**Issue by gr2m** [noBackend/noBackend-app-invoice#7]
I've tried to optimize the example app for adding new implementations of the backend as fast as possible. I've done that with event hooks, like `this.trigger('invoice:save', invoice)`, that the respective backend implementation can subscribe to and make it real, see examples [here](https://github.com/noBackend/example-invoice/blob/gh-pages/nobackend-examples/remoteStorage-Sockethub/script.js#L56) and [here](https://github.com/noBackend/example-invoice/blob/gh-pages/nobackend-examples/hoodie/script.js#L11).

But I think that's not the natural way a frontend developer would do it. What we claim is to build apps with "Dreamcode", meaning just write JavaScript for functionality, even if it does not exist yet. 

So I'd suggest to replace the event hooks with actual code, for example instead of 

``` js
this.trigger('invoice:save', invoice)
```

I'd do something like

``` js
store.save( invoice )
```

I'd also add a blueprint implementation that has all the Dreamcode listet, without any functionality. A noBackend provider could then take this file and overwrite it to make it work for real.

Thoughts? 

@silverbucket

**Comment by silverbucket** [comment]
Hmm,

 In the example `store.save( invoice )` it's not entirely clear that this
is activated on an event, but rather seems that this is a call to store the
document right then.  In that case I think the event listener code makes
more sense for a developer. You create the UI, and when certain elements
are clicked, the even handlers are called.

Or am I misunderstanding?

**Comment by gr2m** [comment]
I'll prepare a pull request to make it more clear what I mean. I think the even triggering / binding is not what a JS developer would do naturally, if all functionality would be available in the browser

**Comment by silverbucket** [comment]
Isn't event based programming quite established in GUI application
development? I'm not traditionally a GUI developer, but I think things like
MS development environment, Adobe, and Objective-C (mac) application
development all make extensive use of the event paradigm. But maybe you're
right, I will wait to see the pull request.

**Comment by gr2m** [comment]
There you go: #8 

It just feels way more native this way to me, from a frontend developer's perspective. Let me know what you think. I'd do the rewrite of the Hoodie & Sockethub + remoteStorage implementation myself, no biggie.

**Comment by gr2m** [comment]
I actually went a head and adjusted the Sockethub + remoteStorage implementation in https://github.com/noBackend/noBackend-app-invoice/commit/c31d4a44b12ca9e66c909bed4d37ea84442c13f9

cool?
